#!/bin/bash
#
# testftrace runs build tests and selftests on qemu

# TODO: check prerequisites

CONFS="$*"

set -e
export LANG=en_US.UTF-8 || export LANG=c

absdir() { # dir
  (cd $1; pwd)
}

TOP_DIR=`dirname $0`
TOP_DIR=`absdir $TOP_DIR`

MINCS_DIR=$TOP_DIR/mincs
ERMINE=$MINCS_DIR/ermine-breeder
LINUX_DIR=$MINCS_DIR/work/linux/linux
FTRACETEST_DIR=$LINUX_DIR/tools/testing/selftests/ftrace
TEST_DIR=${TOP_DIR}/runtest
LOG_DIR=${TEST_DIR}/logs

if [ ! -x $ERMINE ]; then 
	echo "please sync submodule (\`git submodule init && git submodule update\`)"
	exit 1
fi

build_ermine() { # arch config
  set -e
  echo -e "======\n Build kernel ($1, $2) \n======\n"
  $ERMINE --rebuild-kernel --arch $1 --config $2
  echo -e "======\n Successfully build kernel \n======\n"
}

run_ermine() { # arch config
  set -e
  echo -e "======\n Boot and run build kernel ($1, $2) \n======\n"
  $ERMINE testrun --arch $1 --work $TEST_DIR
  echo -e "======\n Successfully boot and run \n======\n"
}

setup_testdir() {
  rm -rf $TEST_DIR/ftrace
  cp -r $FTRACETEST_DIR $TEST_DIR/
}

#BUILD_ARCH="arm arm64 powerpc loongarch riscv i386 x86_64"
BUILD_ARCH=x86_64
RUN_ARCH="arm64 riscv x86_64"

setup_testdir

if [ -z "$CONFS" ]; then
  CONFS="$TOP_DIR/configs/*"
fi

for arch in $BUILD_ARCH; do
  for conf in $CONFS; do
    LOG_DATE=`date +%Y%m%d-%H%M%S`
    mkdir -p $LOG_DIR/$LOG_DATE
    rm -f $LOG_DIR/latest
    (cd $LOG_DIR; ln -s $LOG_DATE latest)
    touch $LOG_DIR/latest/$arch:`basename $conf`

    build_ermine $arch $conf 2>&1 | tee $LOG_DIR/latest/build.log
    if echo $RUN_ARCH | grep -qw $arch ; then
       run_ermine $arch $conf $conf 2>&1 | tee $LOG_DIR/latest/runtest.log
    fi
  done
done
